#!/bin/bash
# This is a script to be used as a pre-commit hook in Git. It scans all XML
# files in the repository and removes any byte-order markers from the files before
# they are committed.
# If you've just cloned this repository, you can use the installHook.sh to install
# this as a pre-commit hook locally.

#echo Running $BASH_SOURCE
#set | egrep GIT
#echo PWD is $PWD
echo "== Looking for Byte Order Markers to remove =="
found=0
for x in $(find . -name '*.xml'); do
 if [[ "$(file "$x")" == *UTF-8\ Unicode\ \(with\ BOM\)* ]]; then
   echo "Removing UTF-8 BOM for $x"
   let "found += 1"
   # The +4 tells it to tail from the 4th byte (skipping BOM)
   tail -c +4 "$x" > "/tmp/killbom" || { echo "Failed to tail to /tmp/killbom"; exit 1; }
   mv "/tmp/killbom" "$x"
   git add "$x"
 fi
done

if [ "$found" -gt "0" ]; then
   echo
   echo " !!! Found $found files with byte-order markers. These have been fixed and updated in the commit and in your working directory !!!"
   echo
else
   echo "No files with byte-order markers found"
fi

exit 0
